version: "3.1"

services:
  openvidu-server:
    image: openvidu/openvidu-server-kms:2.23.0
    container_name: openvidu-server
    ports:
      - "4443:4443"
    environment:
      - OPENVIDU_SECRET=1234
      - OPENVIDU_CDR=true
      - OPENVIDU_CDR_PATH=/opt/openvidu/cdr
      - OPENVIDU_RECORDING=true
      - OPENVIDU_RECORDING_PATH=/opt/openvidu/recordings
      - OPENVIDU_RECORDING_CUSTOM_LAYOUT=/opt/openvidu/custom-layout
      - OPENVIDU_RECORDING_AUTOSTOP_TIMEOUT=120
    volumes:
      - ./openvidu/recordings:/opt/openvidu/recordings
      - ./openvidu/custom-layout:/opt/openvidu/custom-layout
      - ./openvidu/cdr:/opt/openvidu/cdr
      - //var/run/docker.sock:/var/run/docker.sock # for Windows
      # - /var/run/docker.sock:/var/run/docker.sock # for Linux
