x-environments: &default
  env_file: .env # 기본 환경 파일을 지정합니다.

services:
  kms:
    image: kurento/kurento-media-server:latest
    container_name: kms
    expose:
      - "8888"
      - "40000/udp"
    <<: *default
    networks:
      - mynetwork
    
  openvidu-server:
    image: openvidu/openvidu-server:2.28.0
    container_name: openvidu-server
    expose:
      - "5443"
    <<: *default
    networks:
      - mynetwork
    environment:
      - OPENVIDU_SECRET=${OPENVIDU_SECRET}
      - DOMAIN_OR_PUBLIC_IP=${DOMAIN_OR_PUBLIC_IP}
      - KMS_URIS=${KMS_URIS}
      - OPENVIDU_CDR=${OPENVIDU_CDR}
      - OPENVIDU_CDR_PATH=${OPENVIDU_CDR_PATH}
      - OPENVIDU_RECORDING=${OPENVIDU_RECORDING}
      - OPENVIDU_RECORDING_PATH=${OPENVIDU_RECORDING_PATH}
      - OPENVIDU_RECORDING_CUSTOM_LAYOUT=${OPENVIDU_RECORDING_CUSTOM_LAYOUT}
      - OPENVIDU_RECORDING_AUTOSTOP_TIMEOUT=${OPENVIDU_RECORDING_AUTOSTOP_TIMEOUT}
      - SERVER_SSL_ENABLED=${SERVER_SSL_ENABLED}
      - SERVER_PORT=${SERVER_PORT}
    volumes:
      - ./openvidu/recordings:/opt/openvidu/recordings
      - ./openvidu/custom-layout:/opt/openvidu/custom-layout
      - ./openvidu/cdr:/opt/openvidu/cdr
      - //var/run/docker.sock:/var/run/docker.sock # for Linux
    depends_on:
      - kms

networks:
  mynetwork:
    external: true

volumes:
  mysql_data:
